### ISSUE TITLE
wtc插件事件处理异常

### ISSUE THREAD

**Issue by Candy-sky** [BlueNines/WorldListTrashCan#2]
我在我的服务端当中使用了最新版本的wtc插件，正常工作十多天之后，控制台开始汇报插件异常，
我的服务端为1.12.2 catserver 混合端，
具体表现为玩家可见的不间断刷屏，且垃圾桶无法正常工作
意为插件不间断发送“还有1次清理垃圾桶” ”垃圾桶已清理“ ”还有3次清理垃圾桶“ ......
简要错误摘要如下
[16:46:22] [Server thread/WARN] [org.worldlisttrashcan.WorldListTrashCan]: [WorldListTrashCan] Task #6422 for WorldListTrashCan v5.1.3 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at defeatedcrow.hac.food.entity.DrinkEntity.func_70005_c_(DrinkEntity.java:87) ~[DrinkEntity.class:?]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.getName(CraftEntity.java:654) ~[CraftEntity.class:git-CatServer-1.12.2-5a600445]
	at org.worldlisttrashcan.TrashMain.ClearItemsTask$1.run(ClearItemsTask.java:359) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-5a600445]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-5a600445]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:894) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_422]
[完整日志.log](https://github.com/user-attachments/files/17478279/default.log)

**Comment by BlueNines** [comment]
加我QQ， 发我这个版本的jar文件

**Comment by BlueNines** [comment]
报错的解释如下：

**Comment by BlueNines** [comment]
报错的说明如下：
具体到插件的代码行：
意为筛选出黑名单的实体
BlackNameList.contains(entity.getName())
但是你的服务端不知为何，使用entity.getName( )这个方法时，调用了本不应该被调用的客户端逻辑
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n   （client）
请检查你的服务端mods文件夹，是否有客户端模组，并且检查最近几日跟客户端逻辑的相关内容
比如，客户端模组装在了服务端，或是客户端的其他文件装在了服务端
一般来说entity.getName( )是不可能会报错的，除非有模组顶替掉了它的实现
